-- ============================================================================
--  Gemba Walk — ข้อมูลตั้งต้นของจริง (ไม่มีข้อมูลตัวอย่างแล้ว)
--  รันด้วย: wrangler d1 execute gemba-audit --file=./seed.sql --remote
--
--  ที่มาของข้อมูล
--    ผู้ใช้/ผู้ดูแล  ตาราง employees ในฐานข้อมูล psif-db ของโปรเจค PSIF
--                   (393 คน — ตัดแถว RESIGNED-* ที่เป็นช่องว่างสำหรับพนักงานลาออกออกแล้ว)
--    พื้นที่เดิน     6 แห่งตามที่โรงงานกำหนด: VSM1 · VSM2 · VSM3 · VSM4 · QC · OFFICE
--
--  รหัสเข้าระบบ = รหัสพนักงาน เช่น T-815 · L-3611 · PST742 · M-089
--  รหัสเข้าหน้า /admin = รหัสพนักงานของผู้ดูแลระบบ 4 คน (ดูส่วน "ผู้ดูแลระบบ")
--
--  ไฟล์นี้ไม่มีแผน/บันทึกการเดิน/ประวัติใด ๆ ทั้งสิ้น ระบบเริ่มจากศูนย์จริง
--  ทุกคำสั่งใช้ INSERT OR IGNORE จึงรันซ้ำได้ และไม่ทับข้อมูลที่แก้ไปแล้วในแอป
-- ============================================================================


-- ── ตั้งค่าระบบ (แถวเดียวเสมอ) ────────────────────────────────────────────
INSERT OR IGNORE INTO app_settings (id, weekly_target, recent_visit_days, company_name, plant_name) VALUES
  (1, 1, 7, 'TENNECO', 'TENNECO');


-- ── ผู้ดูแลระบบ — เข้าที่ /admin ด้วยรหัสพนักงานของตัวเอง ─────────────────
INSERT OR IGNORE INTO superusers (id, admin_code, full_name) VALUES
  ('su_G_245', 'G-245', 'น.ส.สุมินตรา ชานนท์'),
  ('su_T_738', 'T-738', 'นายสุธีรักษ์ เตยา'),
  ('su_T_798', 'T-798', 'นายชัยสิทธิ์ ด้วงกัน'),
  ('su_T_815', 'T-815', 'นายวิภาวัส จันทะคาม');


-- ── หัวข้อการเดิน 8 หัวข้อ (แก้/เพิ่มได้ในหน้าตั้งค่า) ─────────────────────────
INSERT OR IGNORE INTO walk_themes (id, theme_name, theme_name_en, is_active) VALUES
  ('th_01', '1-Safety: พฤติกรรมความปลอดภัย', '1-Safety: Behaviour Based Safety', 1),
  ('th_02', '2-Safety: การ์ดเครื่องจักร', '2-Safety: Machine Guarding', 1),
  ('th_03', '3-Safety: รถยก/MHE', '3-Safety: MHE/PIVs', 1),
  ('th_04', '4-Quality: ของเสียและงานแก้', '4-Quality: Defect & Rework', 1),
  ('th_05', '5-5ส และความสะอาด', '5-5S & Housekeeping', 1),
  ('th_06', '6-การทำงานตามมาตรฐาน', '6-Standard Work', 1),
  ('th_07', '7-พลังงานและสิ่งแวดล้อม', '7-Energy & Environment', 1),
  ('th_08', '8-การมีส่วนร่วมของพนักงาน', '8-People Engagement', 1);


-- ── พื้นที่เดิน 6 แห่ง (เรียงตามลำดับที่แอปแสดงผล) ───────────────────────────
INSERT OR IGNORE INTO areas (id, area_name, area_name_en, parent_id, department, is_active) VALUES
  ('ar_vsm1', 'VSM1', 'VSM1', NULL, 'VSM1', 1),
  ('ar_vsm2', 'VSM2', 'VSM2', NULL, 'VSM2', 1),
  ('ar_vsm3', 'VSM3', 'VSM3', NULL, 'VSM3', 1),
  ('ar_vsm4', 'VSM4', 'VSM4', NULL, 'VSM4', 1),
  ('ar_qc', 'QC', 'QC', NULL, 'Quality Control', 1),
  ('ar_office', 'OFFICE', 'OFFICE', NULL, 'Office', 1);


-- ── ผู้ใช้ 393 คน จากทะเบียนพนักงาน PSIF ──────────────────────────────────
-- is_active = 0 คือคนที่ปิดบัญชีไว้แล้วในระบบต้นทาง (เข้าระบบไม่ได้)
-- dashboard_enabled = 1 ทุกคน ตามที่ตกลงไว้ว่าให้เห็นภาพรวมทั้งโรงงานได้
--
-- can_login = สิทธิ์เข้าใช้แอป ผู้ดูแลระบบกำหนดเป็นรายคนได้ในหน้าตั้งค่า
--   เปิดไว้ 63 คน = ระดับหัวหน้าขึ้นไปที่ยังทำงานอยู่
--   (ผู้จัดการ · ผู้ดูแลแผนก · หัวหน้าทีม · ผู้ดูแลระบบ · เจ้าหน้าที่ความปลอดภัย)
--   พนักงานอีก 330 คนยังอยู่ในทะเบียนเพื่อเลือกเป็น "ผู้ร่วมเดิน" ได้ แต่ล็อกอินไม่ได้
--   เหตุผล: รหัสเข้าระบบคือรหัสพนักงานซึ่งเดาได้ ถ้าเปิดหมดก็เข้าแทนกันได้ทั้งโรงงาน
INSERT OR IGNORE INTO managers
  (id, manager_code, full_name, full_name_en, department, position, avatar_url, is_active, dashboard_enabled, can_login, created_at)
VALUES
  ('mgr_00', '00', 'Mr.Ivan Klimov', NULL, 'EHS', 'ผู้จัดการ', NULL, 1, 1, 1, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_640005', '640005', 'สุริยัน ศูนย์กลาง', NULL, 'VSM3', 'ผู้จัดการ', NULL, 1, 1, 1, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_G_105', 'G-105', 'นายวิทยา ภิญโญยิ่ง', NULL, 'Warehouse', 'ผู้ดูแลแผนก', NULL, 1, 1, 1, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_G_115', 'G-115', 'นางจินตนา ถาวรศิลป์', NULL, 'Quality Assurance', 'ผู้ดูแลแผนก', NULL, 1, 1, 1, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_G_131', 'G-131', 'น.ส.กษมา ภิรมย์ศรี', NULL, 'Quality Control', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_G_133', 'G-133', 'นายณัฐวุฒิ สุขเนาวรัตน์', NULL, 'IT', 'ผู้ดูแลแผนก', NULL, 1, 1, 1, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_G_134', 'G-134', 'น.ส.อรนุช คำลือเมือง', NULL, 'Quality Control', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_G_186', 'G-186', 'น.ส.สุพรรณรสา คำยม', NULL, 'Accounting', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_G_205', 'G-205', 'น.ส.ปทิตตา พรธาดาศักดิ์', NULL, 'Purchasing', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_G_213', 'G-213', 'นายธีระพล หาสจิตโต', NULL, 'PC', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_G_214', 'G-214', 'นายศรายุธ พวงผกา', NULL, 'Store', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_G_215', 'G-215', 'นายอุดม บุญคง', NULL, 'PC', 'ผู้ดูแลแผนก', NULL, 1, 1, 1, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_G_216', 'G-216', 'น.ส.อลิสา สุภวงษ์', NULL, 'PC', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_G_234', 'G-234', 'นายโกสินทร์ ราชประโคน', NULL, 'Store', 'ผู้จัดการ', NULL, 1, 1, 1, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_G_235', 'G-235', 'น.ส.ณภัทร์ พูลสวัสดิ์', NULL, 'Purchasing', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_G_237', 'G-237', 'น.ส.สราพร อุทัยศรี', NULL, 'PC', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_G_245', 'G-245', 'น.ส.สุมินตรา ชานนท์', NULL, 'HR', 'ผู้ดูแลระบบ', NULL, 1, 1, 1, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_G_246', 'G-246', 'น.ส.ขนิษฐา แท้รัมย์', NULL, 'Customer Service', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_G_250', 'G-250', 'น.ส.ลภัสรดา ทองนอก', NULL, 'Accounting', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_G_252', 'G-252', 'น.ส.พรพิมล โสตกลาง', NULL, 'HR', 'พนักงาน', NULL, 0, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_G_253', 'G-253', 'นางสาวสุกานดา รักษ์ถาวรนันท์', NULL, 'Accounting', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_G_255', 'G-255', 'นางจุฑารัตน์ ศรีบุตรา', NULL, 'EHS', 'เจ้าหน้าที่ความปลอดภัย', NULL, 1, 1, 1, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_G_256', 'G-256', 'น.ส.พณิดา ศรีชมภู', NULL, 'Accounting', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_G_259', 'G-259', 'น.ส.มีนตรา วิเชียรพงษ์', NULL, 'Customer Service', 'ผู้ดูแลแผนก', NULL, 1, 1, 1, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_G_260', 'G-260', 'น.ส.เพชรลดา พรมมา', NULL, 'VSM4', 'ผู้ดูแลแผนก', NULL, 1, 1, 1, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_1058', 'L-1058', 'นายสรศักดิ์ สุริยะ', NULL, 'VSM4', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_1101', 'L-1101', 'นายเดชา คำพิมูล', NULL, 'VSM4', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_1195', 'L-1195', 'น.ส.สุดาภร สุดใจ', NULL, 'VSM3', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_1283', 'L-1283', 'น.ส.ณัชชา สุทธิเจริญ', NULL, 'VSM2', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_1372', 'L-1372', 'นายวิชัย เจริญเขต', NULL, 'VSM3', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_1529', 'L-1529', 'นายสามารถ ครัวจัตุรัส', NULL, 'VSM2', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_1534', 'L-1534', 'น.ส.รัตณาภรณ์ มากเกิด', NULL, 'VSM2', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_1567', 'L-1567', 'นายภาศุ สงค์พิมพ์', NULL, 'VSM3', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_1598', 'L-1598', 'นายสัญญา คิดโสดา', NULL, 'VSM4', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_1606', 'L-1606', 'นายธรรมนูญ พงษ์ไธสง', NULL, 'Quality Control', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_1686', 'L-1686', 'นายคำพันธ์ สาเกตุ', NULL, 'Quality Control', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_1763', 'L-1763', 'นายสมชาย พรมชาติ', NULL, 'VSM4', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_1776', 'L-1776', 'นายประวิง ไฝ่ไร่', NULL, 'Quality Control', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_1787', 'L-1787', 'นายสุทิน แสงสุวรรณ', NULL, 'VSM1', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_1827', 'L-1827', 'นายสุทิศ ภูถมดี', NULL, 'VSM4', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_1839', 'L-1839', 'นายนนทชัย กันกา', NULL, 'Quality Control', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_1876', 'L-1876', 'นายเรวัต หลาบสุภา', NULL, 'VSM2', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_1879', 'L-1879', 'นายวิฑูรย์ สุขเลิศ', NULL, 'VSM4', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_1928', 'L-1928', 'นายกันยา สวนธิ', NULL, 'VSM4', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_1930', 'L-1930', 'นายวสันต์ จันทคีรี', NULL, 'Quality Control', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_1940', 'L-1940', 'นายเพิน ชูสะติ', NULL, 'VSM1', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_2005', 'L-2005', 'นายตรีภพ สมพงษ์', NULL, 'Quality Control', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_2033', 'L-2033', 'นายเอกชัย ประดิษฐ์เทา', NULL, 'VSM3', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_2088', 'L-2088', 'นายยุทธพิชัย สมหวัง', NULL, 'Quality Control', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_2101', 'L-2101', 'นายนพรัตน์ พวงพันธ์', NULL, 'VSM4', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_2136', 'L-2136', 'นายทองพูน เพิ่มพูล', NULL, 'VSM3', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_2155', 'L-2155', 'นายไพศักดิ์ ม่วงอ่อน', NULL, 'VSM1', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_2176', 'L-2176', 'นายโกวิทย์ คำภีร์', NULL, 'VSM2', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_2194', 'L-2194', 'นายทวี จิรัมย์', NULL, 'VSM2', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_2209', 'L-2209', 'นายดุสิต จำรองพันธ์', NULL, 'VSM2', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_2297', 'L-2297', 'นายธนดล สัตบุตร', NULL, 'VSM2', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_2336', 'L-2336', 'นายดำรงค์ฤทธิ์ อินยม', NULL, 'VSM2', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_2352', 'L-2352', 'น.ส.สุภาพร ปานพุ่ม', NULL, 'Quality Control', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_2363', 'L-2363', 'นายคำนึง เพชรประเสริฐ', NULL, 'VSM1', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_2404', 'L-2404', 'นายบรรจง สูแพะ', NULL, 'VSM2', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_2411', 'L-2411', 'นายณรงค์ศักดิ์ พิมพะ', NULL, 'VSM2', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_2429', 'L-2429', 'น.ส.ทองพูน ขุนภักนา', NULL, 'VSM2', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_2446', 'L-2446', 'นายสมเดช สมญา', NULL, 'Quality Control', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_2475', 'L-2475', 'นายวิเศษ เหง้าสุวรรณ', NULL, 'VSM2', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_2480', 'L-2480', 'นายสมคิด ทรทึก', NULL, 'VSM4', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_2488', 'L-2488', 'นายสราวุฒิ ปานทอง', NULL, 'VSM4', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_2499', 'L-2499', 'นายทรงศักดิ์ สืบเสระ', NULL, 'VSM4', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_2539', 'L-2539', 'นายนิพนธ์ สีระพันธ์', NULL, 'Quality Control', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_2553', 'L-2553', 'น.ส.เพ็ญนภา มีพิมพ์', NULL, 'VSM2', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_2566', 'L-2566', 'น.ส.ประภัสสร ศรีสว่าง', NULL, 'VSM2', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_2567', 'L-2567', 'นายสานนท์ พลแสน', NULL, 'Warehouse', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_2598', 'L-2598', 'นายถาวร นิลผาพงษ์', NULL, 'Quality Control', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_2612', 'L-2612', 'นายทัศพงษ์ องอาจ', NULL, 'VSM2', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_2623', 'L-2623', 'น.ส.หยาดพิรุณ สัตถาผล', NULL, 'VSM3', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_2631', 'L-2631', 'นายประยุทธ ฝากาทอง', NULL, 'VSM1', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_2634', 'L-2634', 'นายภูณัทกิจ อ่อนวิมล', NULL, 'VSM4', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_2642', 'L-2642', 'น.ส.เกษร อุ่นมุกดา', NULL, 'Quality Control', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_2658', 'L-2658', 'น.ส.มาลิณี จอดพิมาย', NULL, 'VSM4', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_2659', 'L-2659', 'นายณรงค์ จอดพิมาย', NULL, 'VSM4', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_2677', 'L-2677', 'นายชาคริต บุญศิริกร', NULL, 'VSM4', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_2687', 'L-2687', 'นายโกมิน จันทร์ดี', NULL, 'VSM1', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_2722', 'L-2722', 'นายณรงค์ ปาติตัง', NULL, 'VSM3', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_2734', 'L-2734', 'นายสมพร พุ่มมะลิ', NULL, 'VSM1', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_2737', 'L-2737', 'นายชลาธิป จำเรียง', NULL, 'VSM1', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_2741', 'L-2741', 'นายไพบูลย์ เถาว์โท', NULL, 'Quality Assurance', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_2776', 'L-2776', 'น.ส.อารยา เกือกรัมย์', NULL, 'Quality Control', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_2782', 'L-2782', 'น.ส.วิมล จันทร์สมร', NULL, 'VSM2', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_2796', 'L-2796', 'น.ส.พรทิพย์ หอมจันทร์', NULL, 'Quality Control', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_2809', 'L-2809', 'น.ส.อรชา ทาสีคำ', NULL, 'VSM3', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_2813', 'L-2813', 'น.ส.สุวนันท์ พวงจันทร์', NULL, 'Store', 'ผู้ดูแลแผนก', NULL, 1, 1, 1, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_2818', 'L-2818', 'น.ส.กรชนก กรุดเงิน', NULL, 'VSM2', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_2836', 'L-2836', 'น.ส.ธมลวรรณ ดาวสกุล', NULL, 'VSM2', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_2847', 'L-2847', 'นายวัฒชัย ปิตตาละตัง', NULL, 'Quality Control', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_2851', 'L-2851', 'นายเศรษฐพงศ์ ไพบูลย์', NULL, 'VSM1', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_2861', 'L-2861', 'น.ส.การะเกษ สุโพธิ์', NULL, 'Quality Control', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_2920', 'L-2920', 'น.ส.จิตติมา เปลี่ยนวงษ์', NULL, 'Quality Control', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_2929', 'L-2929', 'นายสุวรรณ สุขสถิตย์', NULL, 'VSM4', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_2935', 'L-2935', 'นายพิสิษฐ์ อิ่มเพ็ง', NULL, 'VSM4', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_2939', 'L-2939', 'น.ส.สุภาพร คิดกล้า', NULL, 'VSM2', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_2972', 'L-2972', 'น.ส.ทัศดี เวียงแก้ว', NULL, 'VSM3', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_2984', 'L-2984', 'น.ส.ขนิษฐา โสคำ', NULL, 'VSM2', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_2995', 'L-2995', 'นายสิงห์สังเวียร จำเริญไกร', NULL, 'VSM2', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_3007', 'L-3007', 'น.ส.กนกพร พุฒทอง', NULL, 'Quality Assurance', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_3012', 'L-3012', 'นายจีราวัฒน์ บวรเกษมพงศ์', NULL, 'VSM4', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_3015', 'L-3015', 'นายวิรุต การุณรัตน์', NULL, 'VSM4', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_3019', 'L-3019', 'น.ส.จันทร์เพ็ญ แสงรส', NULL, 'VSM2', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_3035', 'L-3035', 'นายจักรินทร์ นิสสัยดี', NULL, 'VSM4', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_3045', 'L-3045', 'น.ส.นุจรินทร์ เรืองจันทา', NULL, 'VSM3', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_3062', 'L-3062', 'นายอภิวัฒน์ หาดจันทร์', NULL, 'VSM4', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_3093', 'L-3093', 'นายวิรัช แจ่มจำรัส', NULL, 'VSM3', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_3096', 'L-3096', 'นายบรรหาญ แสงอ่อน', NULL, 'VSM4', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_3101', 'L-3101', 'นายสังสรรค์ จันดี', NULL, 'VSM1', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_3105', 'L-3105', 'นายสุขกมล กาภูคำ', NULL, 'VSM3', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_3114', 'L-3114', 'นายคชา กล้าหาญ', NULL, 'VSM3', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_3169', 'L-3169', 'นายสมพงษ์ ลองพล', NULL, 'VSM3', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_3264', 'L-3264', 'นายประวิท เดชโชค', NULL, 'Quality Control', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_3295', 'L-3295', 'นายชวภณ เสียงเย็น', NULL, 'VSM3', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_3299', 'L-3299', 'นายไพรินทร์ อินทร์ทอง', NULL, 'VSM2', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_3327', 'L-3327', 'นายเนตร์น้อย พรมหากุล', NULL, 'VSM1', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_3330', 'L-3330', 'นายธีรพงษ์ สิงห์สำราญ', NULL, 'VSM3', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_3338', 'L-3338', 'นายปราการณ์ สุริฉาย', NULL, 'Quality Assurance', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_3362', 'L-3362', 'นายสุรสิทธิ์ นรสาร', NULL, 'VSM3', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_3369', 'L-3369', 'นายทิฆัมพร เพสารี', NULL, 'VSM1', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_3374', 'L-3374', 'นายปัญญา ประวันนา', NULL, 'VSM4', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_3377', 'L-3377', 'นายธนภัทร์ หนุนโชค', NULL, 'VSM4', 'พนักงาน', NULL, 0, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_3378', 'L-3378', 'นายจักรพันธ์ เทียนหอม', NULL, 'VSM4', 'ผู้ดูแลแผนก', NULL, 1, 1, 1, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_3383', 'L-3383', 'นายทศพร ประภาวิชา', NULL, 'VSM1', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_3385', 'L-3385', 'นายทักษิณ เพชรโสภา', NULL, 'VSM2', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_3388', 'L-3388', 'นายเสรี สิงห์ชู', NULL, 'Quality Control', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_3394', 'L-3394', 'นายวีระยุทธ งามดี', NULL, 'VSM3', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_3412', 'L-3412', 'น.ส.บังอร แก้ววิเศษ', NULL, 'Quality Control', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_3414', 'L-3414', 'นายพิชิตชัย พรมจันทร์', NULL, 'VSM1', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_3419', 'L-3419', 'นายปัญญา ผจญกิจ', NULL, 'VSM2', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_3422', 'L-3422', 'น.ส.เทียมจิตร นวลอินทร์', NULL, 'VSM2', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_3425', 'L-3425', 'นายโกมน อุ่นสวัสดี', NULL, 'VSM1', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_3429', 'L-3429', 'นายเจริญทอง ปัญหาไชย', NULL, 'VSM1', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_3430', 'L-3430', 'นายปรัชญา ขาวงาม', NULL, 'VSM1', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_3431', 'L-3431', 'นายกฤษณ์ ซื้อจริง', NULL, 'VSM4', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_3442', 'L-3442', 'นางประภาภรณ์ อรุณโรจน์', NULL, 'VSM3', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_3452', 'L-3452', 'นายอิสระ ดัชถุยาวัตร', NULL, 'VSM1', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_3453', 'L-3453', 'นายประจญ ชะตารัมย์', NULL, 'VSM3', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_3455', 'L-3455', 'นายชัชชัย ชนะชัย', NULL, 'VSM3', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_3461', 'L-3461', 'นายสายชล แสงทองไชย์', NULL, 'VSM1', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_3470', 'L-3470', 'นายธงชัย บุญจิตร', NULL, 'VSM2', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_3474', 'L-3474', 'น.ส.อรณี หมู่ศิริ', NULL, 'VSM2', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_3475', 'L-3475', 'นายณัฐวัติ ผดุงภักดี', NULL, 'VSM1', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_3477', 'L-3477', 'นายสำเริง ลักษร', NULL, 'Warehouse', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_3479', 'L-3479', 'นายอลงกรณ์ เทียงดาห์', NULL, 'VSM2', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_3485', 'L-3485', 'นายใกรญษิต พรมทอง', NULL, 'VSM1', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_3495', 'L-3495', 'นายพรประชา ไชยลาด', NULL, 'VSM3', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_3500', 'L-3500', 'นายอัตพล โผภูเขียว', NULL, 'VSM3', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_3501', 'L-3501', 'นายสุภัค โจนรัมย์', NULL, 'VSM4', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_3503', 'L-3503', 'นายศราวุธ แก้วกิ่ง', NULL, 'VSM2', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_3504', 'L-3504', 'ว่าที่ ร.ต.ธานี วงค์วัฒน์', NULL, 'VSM2', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_3508', 'L-3508', 'นายณัฐวัฒน์ พรมสันเทียะ', NULL, 'VSM2', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_3516', 'L-3516', 'นายอำพล เมฆวัน', NULL, 'Quality Control', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_3517', 'L-3517', 'นายเกียรติศักดิ์ เรืองเดชา', NULL, 'VSM1', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_3520', 'L-3520', 'นายนิกูลชัย กองลี', NULL, 'VSM1', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_3522', 'L-3522', 'นายวัฒนา การินทร์', NULL, 'VSM1', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_3523', 'L-3523', 'นายณัฐวุฒิ จันทร์ขำ', NULL, 'Quality Control', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_3525', 'L-3525', 'นายปรนนท์ ชื่นชม', NULL, 'Store', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_3527', 'L-3527', 'นายเกียรติศักดิ์ หล้ามณี', NULL, 'VSM4', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_3528', 'L-3528', 'นายสามารถ สำราญใจ', NULL, 'VSM3', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_3529', 'L-3529', 'นายอาทิตย์ ทองปาน', NULL, 'VSM2', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_3530', 'L-3530', 'นายกลองชัย พันภักดิ์', NULL, 'VSM2', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_3533', 'L-3533', 'นายคมสัน เทียนชัย', NULL, 'VSM3', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_3538', 'L-3538', 'นายพนมพร สมพร', NULL, 'VSM3', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_3539', 'L-3539', 'นายภูริเดช ขันนาค', NULL, 'VSM2', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_3544', 'L-3544', 'นายปรีชา อสิพงษ์', NULL, 'VSM1', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_3546', 'L-3546', 'นายวรพล ทองทา', NULL, 'VSM2', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_3549', 'L-3549', 'นายอภิวัฒน์ พันธ์เดช', NULL, 'VSM2', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_3550', 'L-3550', 'นายวรพันธ์ แฝดสุระ', NULL, 'Quality Control', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_3557', 'L-3557', 'นายพุฒิพงศ์ ภูษี', NULL, 'VSM3', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_3559', 'L-3559', 'นายธนากร สีหานาม', NULL, 'VSM3', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_3561', 'L-3561', 'น.ส.ปิยมาศ จันเรียน', NULL, 'Quality Control', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_3565', 'L-3565', 'นายมงคล เวนุอาธร', NULL, 'VSM3', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_3567', 'L-3567', 'นายพัชกฤตย์ ขันศิลา', NULL, 'VSM3', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_3568', 'L-3568', 'นายอนันต์ ก่อเกิด', NULL, 'VSM1', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_3570', 'L-3570', 'นายอโนทัย กำเพ็ชร', NULL, 'VSM1', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_3571', 'L-3571', 'นายชนกันต์ ผลมีศักดิ์', NULL, 'VSM3', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_3572', 'L-3572', 'น.ส.ดมิสา ศาลางาม', NULL, 'Quality Control', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_3573', 'L-3573', 'นายจตุรทนต์ ปิตะธารา', NULL, 'VSM2', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_3574', 'L-3574', 'นายศราวุฒิ ทองอ้ม', NULL, 'VSM2', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_3576', 'L-3576', 'นายนิพนธ์ ชาญเดช', NULL, 'VSM3', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_3577', 'L-3577', 'นายณัฐสิทธิ์ ผันผาย', NULL, 'VSM1', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_3578', 'L-3578', 'น.ส.ณัฐธยาน์ สุระชาติ', NULL, 'Quality Control', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_3581', 'L-3581', 'นายวิทยา ขันตี', NULL, 'VSM2', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_3582', 'L-3582', 'นายกิตติภพ บัวองค์', NULL, 'VSM4', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_3583', 'L-3583', 'นายวัฒนา สอนไชย', NULL, 'VSM4', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_3584', 'L-3584', 'นายธนากร วรรณทวี', NULL, 'VSM1', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_3586', 'L-3586', 'นายธวัชชัย พิลาพอง', NULL, 'VSM3', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_3587', 'L-3587', 'นายเอกรินทร์ ปัสสาคำ', NULL, 'VSM3', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_3588', 'L-3588', 'นายสุรศักด์ ชมชื่น', NULL, 'VSM1', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_3590', 'L-3590', 'นายศุภกิจ เหลาเพ็ง', NULL, 'VSM2', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_3591', 'L-3591', 'นายณัฐพงษ์ สีสันงาม', NULL, 'VSM4', 'พนักงาน', NULL, 0, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_3594', 'L-3594', 'นางพัชรินทร์ สุขพรรณ์', NULL, 'VSM2', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_3595', 'L-3595', 'นางสาวพินศร มักคะสุด', NULL, 'Quality Control', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_3596', 'L-3596', 'นายคมกฤษ แสนธิ', NULL, 'VSM2', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_3597', 'L-3597', 'นายอนุสรณ์ ขุนจร', NULL, 'VSM3', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_3598', 'L-3598', 'นายอัจฉรา เปร่งเพิ่มพูล', NULL, 'Quality Control', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_3599', 'L-3599', 'นายอภิชัย นาคำมูล', NULL, 'Warehouse', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_3600', 'L-3600', 'นายหงษ์ เนียมชุมแสง', NULL, 'Warehouse', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_3601', 'L-3601', 'นายโพธิ์ไทร แก้ววิเชียร', NULL, 'Warehouse', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_3602', 'L-3602', 'นายประเสริฐ นาจาน', NULL, 'Warehouse', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_3603', 'L-3603', 'นายวีรพล บัวงาม', NULL, 'VSM1', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_3604', 'L-3604', 'นายณัฐพงษ์ ไผ่เรือง', NULL, 'VSM1', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_3605', 'L-3605', 'น.ส.นฤมล ดีเกตุ', NULL, 'VSM2', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_3606', 'L-3606', 'นายอภิสิทธิ์ ป้องศรี', NULL, 'VSM3', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_3607', 'L-3607', 'นายอนุชิต อินทมาตย์', NULL, 'VSM3', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_3608', 'L-3608', 'นายประเวท กิ่งพุ่ม', NULL, 'VSM4', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_3609', 'L-3609', 'นายภคินัย สาผม', NULL, 'VSM4', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_3610', 'L-3610', 'นายวัชรินทร์ คำศรี', NULL, 'VSM4', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_3611', 'L-3611', 'นายธีรพัฒน์ อินทร์สีดา', NULL, 'VSM4', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_603', 'L-603', 'นายรุ่งโรจน์ วรรณสุทธะ', NULL, 'VSM4', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_620', 'L-620', 'นายนิยม เชื้อหนองทอน', NULL, 'VSM1', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_761', 'L-761', 'นายจินดา ไชยพินิจ', NULL, 'VSM2', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_855', 'L-855', 'นายสำเนียง รุ่งเรือง', NULL, 'Quality Control', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_895', 'L-895', 'นายประพันธ์ จันทร์งาม', NULL, 'VSM1', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_896', 'L-896', 'นายสมเพชร แสงสุวรรณ์', NULL, 'VSM1', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_913', 'L-913', 'นายอรุณ อินผ่อง', NULL, 'VSM3', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_L_929', 'L-929', 'นายชัยยุทธิ์ ประสงค์จิรกุล', NULL, 'Quality Control', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_M_036', 'M-036', 'ว่าที่ ร.ต.ธวัชชัย คลังผา', NULL, 'Maintenance', 'ผู้จัดการ', NULL, 1, 1, 1, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_M_057', 'M-057', 'นายมนตรี ปานเจริญ', NULL, 'VSM4', 'ผู้จัดการ', NULL, 0, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_M_065', 'M-065', 'นายศราวุธ สุทธิบูลย์', NULL, 'Process Engineer', 'ผู้จัดการ', NULL, 1, 1, 1, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_M_068', 'M-068', 'นายนิยม ซองพู', NULL, 'Lean', 'ผู้จัดการ', NULL, 1, 1, 1, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_M_072', 'M-072', 'นายดวงชีวิน ประภัสรานันท์', NULL, 'Engineer', 'ผู้จัดการ', NULL, 1, 1, 1, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_M_074', 'M-074', 'น.ส.โชติกา ณ ร้อยเอ็ด', NULL, 'Accounting', 'ผู้จัดการ', NULL, 1, 1, 1, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_M_075', 'M-075', 'นายชัยทัต บุญเจริญ', NULL, 'EHS', 'เจ้าหน้าที่ความปลอดภัย', NULL, 1, 1, 1, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_M_083', 'M-083', 'นายศุภฤกษ์ กุลราตรี', NULL, 'Quality Assurance', 'ผู้จัดการ', NULL, 1, 1, 1, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_M_084', 'M-084', 'น.ส.เปรมยุดา สกุลเดียว', NULL, 'PC', 'ผู้จัดการ', NULL, 1, 1, 1, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_M_085', 'M-085', 'น.ส.ณฐภัทร สุขนิรันดร์กุล', NULL, 'Program', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_M_086', 'M-086', 'นายสุพจน์ ฉ่ำมาลัย', NULL, 'Quality Assurance', 'ผู้จัดการ', NULL, 1, 1, 1, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_M_087', 'M-087', 'นายชานนท์ แสงสุข', NULL, 'VSM2', 'ผู้จัดการ', NULL, 1, 1, 1, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_M_088', 'M-088', 'นายเอกพล วงค์ชนะศรี', NULL, 'VSM1', 'ผู้จัดการ', NULL, 1, 1, 1, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_M_089', 'M-089', 'นายสัญญา ทองนอก', NULL, 'Maintenance', 'ผู้จัดการ', NULL, 1, 1, 1, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_PST189', 'PST189', 'นายเกียรติศักดิ์ แก้วประทุม', NULL, 'VSM1', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_PST596', 'PST596', 'นางสาววิภาดา ชัยสีหา', NULL, 'VSM1', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_PST621', 'PST621', 'นายเอกลักษณ์ พงษ์ธนู', NULL, 'VSM2', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_PST630', 'PST630', 'นายสะอาด นาบำรุง', NULL, 'Warehouse', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_PST640', 'PST640', 'นายอัษฎาวุธ ราศรี', NULL, 'VSM2', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_PST650', 'PST650', 'นายบุรัญ หาริวงค์', NULL, 'VSM3', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_PST654', 'PST654', 'นายอดิศักดิ์ แสงขาว', NULL, 'VSM2', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_PST658', 'PST658', 'นายลิขิต สถิตชัย', NULL, 'VSM1', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_PST664', 'PST664', 'นายวีรพล บัวงาม', NULL, 'VSM1', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_PST667', 'PST667', 'นายณัฐพงษ์ ไผ่เรือง', NULL, 'VSM1', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_PST684', 'PST684', 'นายชโนทัย สุขสมบัติ', NULL, 'VSM3', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_PST694', 'PST694', 'นายพงษ์สวัสดิ์ ชะนะเคน', NULL, 'VSM1', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_PST702', 'PST702', 'นายธีรพัฒน์ อินทร์สีดา', NULL, 'VSM4', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_PST704', 'PST704', 'นายธีรพงศ์ ทำเจริญตระกูล', NULL, 'VSM2', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_PST707', 'PST707', 'นายกิจชนะ ยันรัมย์', NULL, 'VSM1', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_PST708', 'PST708', 'นายวชิระ ศรีนอก', NULL, 'VSM2', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_PST709', 'PST709', 'นายวัชรินทร์ ยอดดี', NULL, 'VSM4', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_PST711', 'PST711', 'นายกิตติพงษ์ นุชเฉย', NULL, 'VSM2', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_PST717', 'PST717', 'นางสาวนฤมล ดีเกตุ', NULL, 'VSM2', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_PST742', 'PST742', 'นางสาวจีรนันท์ ลดาพัน', NULL, 'VSM4', 'เจ้าหน้าที่ความปลอดภัย', NULL, 1, 1, 1, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_PST743', 'PST743', 'นายพัฒนกร ศิริเวช', NULL, 'VSM3', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_PST745', 'PST745', 'นายธีรศักดิ์ สุขไชยสงค์', NULL, 'VSM1', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_PST746', 'PST746', 'นายเสฏฐพงศ์ กอมาตย์', NULL, 'VSM1', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_PST747', 'PST747', 'นายวิชญ์พล ภูกระบิล', NULL, 'VSM1', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_PST748', 'PST748', 'นายสมหมาย สุขแสวง', NULL, 'VSM1', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_PST749', 'PST749', 'นางสาวอรัญญา อินศวร', NULL, 'VSM2', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_PST750', 'PST750', 'นายกิตติศักดิ์ บูรณะ', NULL, 'VSM2', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_PST751', 'PST751', 'นายฉัตรชัย เชียงริน', NULL, 'VSM3', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_PST752', 'PST752', 'นายพิษณุ พิมมะทา', NULL, 'VSM3', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_PST753', 'PST753', 'นายทวีวัฒน์ นักบุญ', NULL, 'VSM3', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_PST755', 'PST755', 'นายอำนาจ ดำรงกิจ', NULL, 'VSM4', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_PST756', 'PST756', 'นายสมพล ทองสุด', NULL, 'VSM1', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_PST759', 'PST759', 'นายเอกชัย โก้พิมาย', NULL, 'VSM4', 'พนักงาน', NULL, 0, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_PST760', 'PST760', 'นายชัยยงค์ มณีใส', NULL, 'VSM2', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_PST761', 'PST761', 'นายธีรวัฒน์ อ้นป้อม', NULL, 'Warehouse', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_PST762', 'PST762', 'นายธวัชชัย กองเพชร', NULL, 'VSM1', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_PST763', 'PST763', 'นายถิรธรรม ทองพา', NULL, 'VSM2', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_PST765', 'PST765', 'น.ส.สุภาศิลป์ ชาคาน', NULL, 'VSM2', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_PST767', 'PST767', 'นายกล้าณรงค์ ภูบังดาว', NULL, 'Maintenance', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_PST768', 'PST768', 'นายพันธกานต์ วงษ์พยัคฆ์', NULL, 'Maintenance', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_PST771', 'PST771', 'นายประเสริฐศักดิ์ สมบัติ', NULL, 'VSM3', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_PST773', 'PST773', 'นายสุรพงศ์ คำดี', NULL, 'VSM3', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_PST774', 'PST774', 'นายทัศนพล หงส์ชุม', NULL, 'VSM3', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_PST776', 'PST776', 'นายเกียรติศักดิ์ ทองยิ่ง', NULL, 'VSM2', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_PST779', 'PST779', 'นายเจตนิพัทธ์ ชมพู', NULL, 'VSM2', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_PST780', 'PST780', 'นายวัชรพล แอมรัมย์', NULL, 'VSM2', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_PST782', 'PST782', 'นายพายุ กุลอัก', NULL, 'VSM3', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_PST784', 'PST784', 'นายวินัฐ สิงห์ลี', NULL, 'VSM2', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_PST786', 'PST786', 'นางสาวอังควิภา จามะรีย์', NULL, 'Quality Control', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_PST789', 'PST789', 'นายภานุพงษ์ การงาน', NULL, 'VSM2', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_PST791', 'PST791', 'นายคธาวุธ กล่ำเชย', NULL, 'VSM2', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_PST794', 'PST794', 'นายพุฒิพงษ์ ฝากเมีย', NULL, 'VSM3', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_PST796', 'PST796', 'นายศุภวิชญ์ แก้วพิลา', NULL, 'VSM1', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_PST797', 'PST797', 'นายพงษ์พิสุทธิ์ ยิ่งสำราญ', NULL, 'VSM1', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_PST798', 'PST798', 'นายณัฐพงษ์ ศรีปราชญ์', NULL, 'VSM3', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_PST799', 'PST799', 'นายรภีพัฒน์ ขุมเงิน', NULL, 'VSM3', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_PST800', 'PST800', 'นายปฏิพล แกมชัยภูมิ', NULL, 'VSM3', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_PST801', 'PST801', 'นายปราโมทย์ อินธิไชย', NULL, 'VSM3', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_PST802', 'PST802', 'นายวรรณชัย โพธิ์หล้า', NULL, 'VSM4', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_PST804', 'PST804', 'นายณัฐพล บัวลี', NULL, 'VSM1', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_PST805', 'PST805', 'นางสาววิมลพรรณ เพชรสังหาร', NULL, 'VSM2', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_PST807', 'PST807', 'นายจักรพันธ์ แก่นจันทร์', NULL, 'VSM3', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_PST808', 'PST808', 'นายนาทนิรันดร์ จำปาแก้ว', NULL, 'VSM3', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_PST810', 'PST810', 'นายเจษฎา กาบแก้ว', NULL, 'VSM1', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_PST811', 'PST811', 'นายวัชรินทร์ สุขบรรณ์', NULL, 'VSM2', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_PST812', 'PST812', 'นายภูวดล พริ้งเพราะ', NULL, 'VSM3', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_PST814', 'PST814', 'นายสุชิน อินธิราช', NULL, 'VSM4', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_S_019', 'S-019', 'นายไสว พลทิแสง', NULL, 'Quality Control', 'หัวหน้าทีม', NULL, 1, 1, 1, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_S_027', 'S-027', 'นายเสถียน ใจกล้า', NULL, 'Quality Control', 'หัวหน้าทีม', NULL, 1, 1, 1, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_S_033', 'S-033', 'นายพอเจตน์ ใจบุญ', NULL, 'VSM1', 'หัวหน้าทีม', NULL, 1, 1, 1, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_S_035', 'S-035', 'นายประทาน นามวงษา', NULL, 'Quality Control', 'หัวหน้าทีม', NULL, 1, 1, 1, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_S_036', 'S-036', 'นายสมพร พรประไพ', NULL, 'VSM1', 'หัวหน้าทีม', NULL, 1, 1, 1, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_S_038', 'S-038', 'นายณรงค์ งิ้วเขียว', NULL, 'VSM4', 'หัวหน้าทีม', NULL, 1, 1, 1, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_S_040', 'S-040', 'นายชลธี สุวรรณไตรย์', NULL, 'Quality Control', 'หัวหน้าทีม', NULL, 1, 1, 1, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_S_041', 'S-041', 'นายสุทิน จันทร์ดี', NULL, 'VSM2', 'หัวหน้าทีม', NULL, 1, 1, 1, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_S_042', 'S-042', 'นายนิคม ปะเทสังข์', NULL, 'VSM1', 'หัวหน้าทีม', NULL, 1, 1, 1, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_S_043', 'S-043', 'นายสุวัลลภ ก้าวธรรม', NULL, 'VSM2', 'หัวหน้าทีม', NULL, 1, 1, 1, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_S_044', 'S-044', 'นายสมยศ แดงสูงเนิน', NULL, 'VSM3', 'หัวหน้าทีม', NULL, 1, 1, 1, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_S_046', 'S-046', 'นายสมศักดิ์ เครือลัดดา', NULL, 'VSM4', 'หัวหน้าทีม', NULL, 1, 1, 1, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_S_047', 'S-047', 'นายกำปั่น เจือจาน', NULL, 'VSM3', 'หัวหน้าทีม', NULL, 1, 1, 1, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_S_050', 'S-050', 'นายสิทธิพล หมอกมืด', NULL, 'VSM1', 'หัวหน้าทีม', NULL, 1, 1, 1, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_S_051', 'S-051', 'นายฐิติศักดิ์ ปรางมาศ', NULL, 'VSM3', 'หัวหน้าทีม', NULL, 1, 1, 1, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_S_053', 'S-053', 'นายภูเบศร์ เรือนไทย', NULL, 'VSM2', 'หัวหน้าทีม', NULL, 1, 1, 1, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_S_054', 'S-054', 'นายรังสรรค์ ดุลมา', NULL, 'Quality Control', 'หัวหน้าทีม', NULL, 1, 1, 1, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_S_055', 'S-055', 'นายวีรศักดิ์ สัตนาโค', NULL, 'VSM3', 'หัวหน้าทีม', NULL, 1, 1, 1, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_S_056', 'S-056', 'นายสุรชัย เจริญจิตต์', NULL, 'VSM3', 'หัวหน้าทีม', NULL, 1, 1, 1, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_S_059', 'S-059', 'นายเกรียงไกร โพธิ์ศรี', NULL, 'VSM4', 'หัวหน้าทีม', NULL, 1, 1, 1, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_S_060', 'S-060', 'นายอนุสรณ์ การรัตน์', NULL, 'VSM1', 'หัวหน้าทีม', NULL, 1, 1, 1, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_S_061', 'S-061', 'นายวิสันต์ กันนุฬา', NULL, 'VSM2', 'หัวหน้าทีม', NULL, 1, 1, 1, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_S_063', 'S-063', 'นายมนูน อินทร์โสภา', NULL, 'VSM2', 'หัวหน้าทีม', NULL, 1, 1, 1, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_S_064', 'S-064', 'นายบุญเลิศ สุขสมัย', NULL, 'VSM2', 'หัวหน้าทีม', NULL, 1, 1, 1, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_S_065', 'S-065', 'นายสัมฤทธิ์ ตอรัมย์', NULL, 'VSM3', 'หัวหน้าทีม', NULL, 1, 1, 1, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_S_067', 'S-067', 'นายจำเนียร ทาเทพ', NULL, 'VSM4', 'หัวหน้าทีม', NULL, 1, 1, 1, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_S_069', 'S-069', 'น.ส.อทิตยา ศรสิทธิ์', NULL, 'VSM3', 'ผู้ดูแลแผนก', NULL, 1, 1, 1, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_S_070', 'S-070', 'นายถาวร นิลผาพงษ์', NULL, 'Quality Control', 'หัวหน้าทีม', NULL, 1, 1, 1, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_S_071', 'S-071', 'ณรงค์ฤทธิ์ อินทิจันทร์', NULL, 'VSM4', 'หัวหน้าทีม', NULL, 1, 1, 1, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_T_188', 'T-188', 'นายเมธา ชมรุกข์', NULL, 'Quality Assurance', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_T_204', 'T-204', 'นายวิรัตน์ หวังชอบ', NULL, 'VSM4', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_T_235', 'T-235', 'นายภิญโญ รักษานนท์', NULL, 'Quality Assurance', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_T_317', 'T-317', 'นายคงกฤช จิตต์หลัง', NULL, 'Maintenance', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_T_329', 'T-329', 'นายสมนึก กลิ่นรื่น', NULL, 'VSM1', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_T_334', 'T-334', 'นายบัณฑิต ศรีสงคราม', NULL, 'VSM3', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_T_368', 'T-368', 'นายวันชัย จันทร์สว่าง', NULL, 'VSM3', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_T_384', 'T-384', 'นายมงคล กุศล', NULL, 'Quality Assurance', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_T_411', 'T-411', 'นายวิเชียร ศรีโยธา', NULL, 'Quality Assurance', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_T_441', 'T-441', 'นายธนาศักดิ์ สุกระวัน', NULL, 'VSM4', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_T_443', 'T-443', 'นายอภิเดช ฉวิกขุนรัมย์', NULL, 'Quality Assurance', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_T_544', 'T-544', 'นายเลิศวิทย์ เริ่มคิดการณ์', NULL, 'Quality Assurance', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_T_545', 'T-545', 'นายวีรเดช วงค์กองแก้ว', NULL, 'Quality Assurance', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_T_550', 'T-550', 'นายชลวุธ หมั่นนอก', NULL, 'Maintenance', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_T_570', 'T-570', 'นายประพันธ์ ทองพูน', NULL, 'Maintenance', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_T_571', 'T-571', 'นายสมยศ เอกจู', NULL, 'Maintenance', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_T_586', 'T-586', 'นายพงศธร วงษ์มณี', NULL, 'Quality Assurance', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_T_604', 'T-604', 'นายวาทิศ วินทไชย', NULL, 'Quality Control', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_T_629', 'T-629', 'นายทนงค์ ลิมสกุล', NULL, 'Maintenance', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_T_644', 'T-644', 'นายชัชวาลย์ เชื้อกลางใหญ่', NULL, 'VSM3', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_T_654', 'T-654', 'นายพฤฒิภัค พุ่มพฤกษ์', NULL, 'Quality Assurance', 'ผู้ดูแลแผนก', NULL, 1, 1, 1, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_T_692', 'T-692', 'นายกฤษณะ ปรินแคน', NULL, 'Quality Assurance', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_T_694', 'T-694', 'นายวันชัย ธรรมวงษี', NULL, 'Quality Assurance', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_T_699', 'T-699', 'นายอนุวัฒน์ มุกดา', NULL, 'Maintenance', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_T_700', 'T-700', 'นายนพพล ตามูล', NULL, 'Maintenance', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_T_706', 'T-706', 'นายคมกฤช บุญมา', NULL, 'Engineer', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_T_707', 'T-707', 'นายวสันต์ สาสอน', NULL, 'Maintenance', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_T_713', 'T-713', 'นายสุริยัน เกตุประยูร', NULL, 'Engineer', 'ผู้ดูแลแผนก', NULL, 1, 1, 1, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_T_725', 'T-725', 'นายมนตรี ผอบเพ็ชร', NULL, 'Maintenance', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_T_726', 'T-726', 'นายอนันต์ คุ้มทรัพย์', NULL, 'Maintenance', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_T_735', 'T-735', 'นายพินิจพันธ์ เพ่งพินิจ', NULL, 'Quality Assurance', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_T_737', 'T-737', 'นายชัยวัฒน์ กลยนี', NULL, 'Maintenance', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_T_738', 'T-738', 'นายสุธีรักษ์ เตยา', NULL, 'Process Engineer', 'ผู้ดูแลระบบ', NULL, 1, 1, 1, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_T_743', 'T-743', 'นายนพรัตน์ สาธุจรัญ', NULL, 'Quality Assurance', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_T_750', 'T-750', 'นายรัชต์พงษ์ บุญโชติ', NULL, 'Quality Assurance', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_T_751', 'T-751', 'นายบุญฤทธิ์ ชูสนุก', NULL, 'Process Engineer', 'ผู้ดูแลแผนก', NULL, 1, 1, 1, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_T_758', 'T-758', 'นายศตวรรษ วิจิตรวรฉัตร', NULL, 'Maintenance', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_T_776', 'T-776', 'นายกิตติ พันธ์คำเกิด', NULL, 'Quality Assurance', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_T_778', 'T-778', 'นายเพิ่มพล พลอยสุวรรณ์', NULL, 'Maintenance', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_T_783', 'T-783', 'นายกิตติธร ทรัพย์ช่วย', NULL, 'Maintenance', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_T_786', 'T-786', 'นายอนุวัฒน์ ศรีสุวรรณชัย', NULL, 'Maintenance', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_T_787', 'T-787', 'นายภูวดล ดงอนนท์', NULL, 'Maintenance', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_T_791', 'T-791', 'นายมณูศักดิ์ คำค้อ', NULL, 'Maintenance', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_T_792', 'T-792', 'นายณัฐพงษ์ รูปสิงห์', NULL, 'Maintenance', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_T_793', 'T-793', 'นายสุทิน ใสนวน', NULL, 'Maintenance', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_T_795', 'T-795', 'นายเพชร ครองชื่น', NULL, 'Maintenance', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_T_797', 'T-797', 'นายชัยยุทธ น้อมกลาง', NULL, 'Quality Assurance', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_T_798', 'T-798', 'นายชัยสิทธิ์ ด้วงกัน', NULL, 'Process Engineer', 'ผู้ดูแลระบบ', NULL, 1, 1, 1, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_T_801', 'T-801', 'นายอภินิชย์ ลุนสิน', NULL, 'Maintenance', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_T_802', 'T-802', 'นายชนาพร ทองจิตร', NULL, 'Maintenance', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_T_804', 'T-804', 'นายณัฐปกรณ์ แสงทอง', NULL, 'Maintenance', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_T_805', 'T-805', 'นายณัฐนันท์ วงศ์เครือศร', NULL, 'Maintenance', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_T_806', 'T-806', 'นายถิรวัฒน์ ไชยพันธ์', NULL, 'Maintenance', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_T_807', 'T-807', 'นายณัฐพงษ์ สอนนนฐี', NULL, 'Maintenance', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_T_808', 'T-808', 'นายกิติพันธ์ ดุลแสง', NULL, 'Maintenance', 'ผู้ดูแลแผนก', NULL, 1, 1, 1, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_T_809', 'T-809', 'นายอนุชา อุ้มหอบ', NULL, 'Maintenance', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_T_812', 'T-812', 'นายกรินทร์ เครือทอง', NULL, 'Quality Assurance', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_T_813', 'T-813', 'น.ส.ศันสนีย์ ดวงจินดา', NULL, 'Quality Assurance', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_T_814', 'T-814', 'นายพรชัย ครองใจ', NULL, 'VSM3', 'พนักงาน', NULL, 1, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_T_815', 'T-815', 'นายวิภาวัส จันทะคาม', NULL, 'VSM4', 'ผู้ดูแลระบบ', NULL, 1, 1, 1, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_T_816', 'T-816', 'ภาสกร อิ่มบูรณาประวัติ', NULL, 'VSM1', 'หัวหน้าทีม', NULL, 1, 1, 1, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('mgr_Temp117', 'Temp117', 'นายคมกริช มุ่งงาม', NULL, 'VSM4', 'พนักงาน', NULL, 0, 1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now'));


-- ── จุดรวมปัญหา: ผู้รับเรื่องตั้งต้น = T-815 (เปลี่ยนได้ที่หน้าตั้งค่า › ระบบ) ──
-- ใส่ท้ายไฟล์เพราะต้องมีทะเบียนผู้ใช้ก่อน · ไม่ทับค่าที่ผู้ดูแลตั้งไว้แล้ว
UPDATE app_settings
   SET issue_owner_id = 'mgr_T_815'
 WHERE id = 1
   AND issue_owner_id IS NULL
   AND EXISTS (SELECT 1 FROM managers WHERE id = 'mgr_T_815');
